---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grocery-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grocery-app
  template:
    metadata:
      labels:
        app: grocery-app
    spec:
      containers:
      - name: grocery-app
        image: decsika/grocery-appv1:latest
        ports:
        - containerPort: 3000   # Use port 3000

---
apiVersion: v1
kind: Service
metadata:
  name: grocery-app-service
spec:
  selector:
    app: grocery-app
  ports:
  - protocol: TCP
    port: 80                 # Expose port 80
    targetPort: 4173
  type: LoadBalancer
